'use strict';

/**
 * @ngdoc function
 * @name findentitiesApp.controller:MainCtrl
 * @description
 * # MainCtrl
 * Controller of the findentitiesApp
 */
angular.module('findentitiesApp')
  .controller('MainCtrl', ['$scope', function ($scope) {
    $scope.entities = [
      {'name': '&amp;',
       'number': '&#38;',
       'description': 'ampersand'},
      {'name': '&gt;',
       'number': '&#62;',
       'description': 'greater-than sign'},
      {'name': '&lt;',
       'number': '&#60;',
       'description': 'less-than sign'},
      {'name': '&quot;',
       'number': '&#34;',
       'description': 'quotation mark = APL quote'},
      {'name': '&acute;',
       'number': '&#180;',
       'description': 'acute accent = spacing acute'},
      {'name': '&cedil;',
       'number': '&#184;',
       'description': 'cedilla = spacing cedilla'},
      {'name': '&circ;',
       'number': '&#710;',
       'description': 'modifier letter circumflex accent'},
      {'name': '&macr;',
       'number': '&#175;',
       'description': 'macron = spacing macron = overline = APL overbar'},
      {'name': '&middot;',
       'number': '&#183;',
       'description': 'middle dot = Georgian comma = Greek middle dot'},
      {'name': '&tilde;',
       'number': '&#732;',
       'description': 'small tilde'},
      {'name': '&uml;',
       'number': '&#168;',
       'description': 'diaeresis = spacing diaeresis'},
      {'name': '&Aacute;',
       'number': '&#193;',
       'description': 'latin capital letter A with acute'},
      {'name': '&aacute;',
       'number': '&#225;',
       'description': 'latin small letter a with acute'},
      {'name': '&Acirc;',
       'number': '&#194;',
       'description': 'latin capital letter A with circumflex'},
      {'name': '&acirc;',
       'number': '&#226;',
       'description': 'latin small letter a with circumflex'},
      {'name': '&AElig;',
       'number': '&#198;',
       'description': 'latin capital letter AE = latin capital ligature AE'},
      {'name': '&aelig;',
       'number': '&#230;',
       'description': 'latin small letter ae = latin small ligature ae'},
      {'name': '&Agrave;',
       'number': '&#192;',
       'description': 'latin capital letter A with grave = latin capital letter A grave'},
      {'name': '&agrave;',
       'number': '&#224;',
       'description': 'latin small letter a with grave = latin small letter a grave'},
      {'name': '&Aring;',
       'number': '&#197;',
       'description': 'latin capital letter A with ring above = latin capital letter A ring'},
      {'name': '&aring;',
       'number': '&#229;',
       'description': 'latin small letter a with ring above = latin small letter a ring'},
      {'name': '&Atilde;',
       'number': '&#195;',
       'description': 'latin capital letter A with tilde'},
      {'name': '&atilde;',
       'number': '&#227;',
       'description': 'latin small letter a with tilde'},
      {'name': '&Auml;',
       'number': '&#196;',
       'description': 'latin capital letter A with diaeresis'},
      {'name': '&auml;',
       'number': '&#228;',
       'description': 'latin small letter a with diaeresis'},
      {'name': '&Ccedil;',
       'number': '&#199;',
       'description': 'latin capital letter C with cedilla'},
      {'name': '&ccedil;',
       'number': '&#231;',
       'description': 'latin small letter c with cedilla'},
      {'name': '&Eacute;',
       'number': '&#201;',
       'description': 'latin capital letter E with acute'},
      {'name': '&eacute;',
       'number': '&#233;',
       'description': 'latin small letter e with acute'},
      {'name': '&Ecirc;',
       'number': '&#202;',
       'description': 'latin capital letter E with circumflex'},
      {'name': '&ecirc;',
       'number': '&#234;',
       'description': 'latin small letter e with circumflex'},
      {'name': '&Egrave;',
       'number': '&#200;',
       'description': 'latin capital letter E with grave'},
      {'name': '&egrave;',
       'number': '&#232;',
       'description': 'latin small letter e with grave'},
      {'name': '&ETH;',
       'number': '&#208;',
       'description': 'latin capital letter ETH'},
      {'name': '&eth;',
       'number': '&#240;',
       'description': 'latin small letter eth'},
      {'name': '&Euml;',
       'number': '&#203;',
       'description': 'latin capital letter E with diaeresis'},
      {'name': '&euml;',
       'number': '&#235;',
       'description': 'latin small letter e with diaeresis'},
      {'name': '&Iacute;',
       'number': '&#205;',
       'description': 'latin capital letter I with acute'},
      {'name': '&iacute;',
       'number': '&#237;',
       'description': 'latin small letter i with acute'},
      {'name': '&Icirc;',
       'number': '&#206;',
       'description': 'latin capital letter I with circumflex'},
      {'name': '&icirc;',
       'number': '&#238;',
       'description': 'latin small letter i with circumflex'},
      {'name': '&Igrave;',
       'number': '&#204;',
       'description': 'latin capital letter I with grave'},
      {'name': '&igrave;',
       'number': '&#236;',
       'description': 'latin small letter i with grave'},
      {'name': '&Iuml;',
       'number': '&#207;',
       'description': 'latin capital letter I with diaeresis'},
      {'name': '&iuml;',
       'number': '&#239;',
       'description': 'latin small letter i with diaeresis'},
      {'name': '&Ntilde;',
       'number': '&#209;',
       'description': 'latin capital letter N with tilde'},
      {'name': '&ntilde;',
       'number': '&#241;',
       'description': 'latin small letter n with tilde'},
      {'name': '&Oacute;',
       'number': '&#211;',
       'description': 'latin capital letter O with acute'},
      {'name': '&oacute;',
       'number': '&#243;',
       'description': 'latin small letter o with acute'},
      {'name': '&Ocirc;',
       'number': '&#212;',
       'description': 'latin capital letter O with circumflex'},
      {'name': '&ocirc;',
       'number': '&#244;',
       'description': 'latin small letter o with circumflex'},
      {'name': '&OElig;',
       'number': '&#338;',
       'description': 'latin capital ligature OE'},
      {'name': '&oelig;',
       'number': '&#339;',
       'description': 'latin small ligature oe (note)'},
      {'name': '&Ograve;',
       'number': '&#210;',
       'description': 'latin capital letter O with grave'},
      {'name': '&ograve;',
       'number': '&#242;',
       'description': 'latin small letter o with grave'},
      {'name': '&Oslash;',
       'number': '&#216;',
       'description': 'latin capital letter O with stroke = latin capital letter O slash'},
      {'name': '&oslash;',
       'number': '&#248;',
       'description': 'latin small letter o with stroke, = latin small letter o slash'},
      {'name': '&Otilde;',
       'number': '&#213;',
       'description': 'latin capital letter O with tilde'},
      {'name': '&otilde;',
       'number': '&#245;',
       'description': 'latin small letter o with tilde'},
      {'name': '&Ouml;',
       'number': '&#214;',
       'description': 'latin capital letter O with diaeresis'},
      {'name': '&ouml;',
       'number': '&#246;',
       'description': 'latin small letter o with diaeresis'},
      {'name': '&Scaron;',
       'number': '&#352;',
       'description': 'latin capital letter S with caron'},
      {'name': '&scaron;',
       'number': '&#353;',
       'description': 'latin small letter s with caron'},
      {'name': '&szlig;',
       'number': '&#223;',
       'description': 'latin small letter sharp s = ess-zed'},
      {'name': '&THORN;',
       'number': '&#222;',
       'description': 'latin capital letter THORN'},
      {'name': '&thorn;',
       'number': '&#254;',
       'description': 'latin small letter thorn'},
      {'name': '&Uacute;',
       'number': '&#218;',
       'description': 'latin capital letter U with acute'},
      {'name': '&uacute;',
       'number': '&#250;',
       'description': 'latin small letter u with acute'},
      {'name': '&Ucirc;',
       'number': '&#219;',
       'description': 'latin capital letter U with circumflex'},
      {'name': '&ucirc;',
       'number': '&#251;',
       'description': 'latin small letter u with circumflex'},
      {'name': '&Ugrave;',
       'number': '&#217;',
       'description': 'latin capital letter U with grave'},
      {'name': '&ugrave;',
       'number': '&#249;',
       'description': 'latin small letter u with grave'},
      {'name': '&Uuml;',
       'number': '&#220;',
       'description': 'latin capital letter U with diaeresis'},
      {'name': '&uuml;',
       'number': '&#252;',
       'description': 'latin small letter u with diaeresis'},
      {'name': '&Yacute;',
       'number': '&#221;',
       'description': 'latin capital letter Y with acute'},
      {'name': '&yacute;',
       'number': '&#253;',
       'description': 'latin small letter y with acute'},
      {'name': '&yuml;',
       'number': '&#255;',
       'description': 'latin small letter y with diaeresis'},
      {'name': '&Yuml;',
       'number': '&#376;',
       'description': 'latin capital letter Y with diaeresis'},
      {'name': '&cent;',
       'number': '&#162;',
       'description': 'cent sign'},
      {'name': '&curren;',
       'number': '&#164;',
       'description': 'currency sign'},
      {'name': '&euro;',
       'number': '&#8364;',
       'description': 'euro sign'},
      {'name': '&pound;',
       'number': '&#163;',
       'description': 'pound sign'},
      {'name': '&yen;',
       'number': '&#165;',
       'description': 'yen sign = yuan sign'},
      {'name': '&brvbar;',
       'number': '&#166;',
       'description': 'broken bar = broken vertical bar'},
      {'name': '&bull;',
       'number': '&#8226;',
       'description': 'bullet = black small circle (note)'},
      {'name': '&copy;',
       'number': '&#169;',
       'description': 'copyright sign'},
      {'name': '&dagger;',
       'number': '&#8224;',
       'description': 'dagger'},
      {'name': '&Dagger;',
       'number': '&#8225;',
       'description': 'double dagger'},
      {'name': '&frasl;',
       'number': '&#8260;',
       'description': 'fraction slash'},
      {'name': '&hellip;',
       'number': '&#8230;',
       'description': 'horizontal ellipsis = three dot leader'},
      {'name': '&iexcl;',
       'number': '&#161;',
       'description': 'inverted exclamation mark'},
      {'name': '&image;',
       'number': '&#8465;',
       'description': 'blackletter capital I = imaginary part'},
      {'name': '&iquest;',
       'number': '&#191;',
       'description': 'inverted question mark = turned question mark'},
      {'name': '&lrm;',
       'number': '&#8206;',
       'description': 'left-to-right mark (for formatting only)'},
      {'name': '&mdash;',
       'number': '&#8212;',
       'description': 'em dash'},
      {'name': '&ndash;',
       'number': '&#8211;',
       'description': 'en dash'},
      {'name': '&not;',
       'number': '&#172;',
       'description': 'not sign'},
      {'name': '&oline;',
       'number': '&#8254;',
       'description': 'overline = spacing overscore'},
      {'name': '&ordf;',
       'number': '&#170;',
       'description': 'feminine ordinal indicator'},
      {'name': '&ordm;',
       'number': '&#186;',
       'description': 'masculine ordinal indicator'},
      {'name': '&para;',
       'number': '&#182;',
       'description': 'pilcrow sign = paragraph sign'},
      {'name': '&permil;',
       'number': '&#8240;',
       'description': 'per mille sign'},
      {'name': '&prime;',
       'number': '&#8242;',
       'description': 'prime = minutes = feet'},
      {'name': '&Prime;',
       'number': '&#8243;',
       'description': 'double prime = seconds = inches'},
      {'name': '&real;',
       'number': '&#8476;',
       'description': 'blackletter capital R = real part symbol'},
      {'name': '&reg;',
       'number': '&#174;',
       'description': 'registered sign = registered trade mark sign'},
      {'name': '&rlm;',
       'number': '&#8207;',
       'description': 'right-to-left mark (for formatting only)'},
      {'name': '&sect;',
       'number': '&#167;',
       'description': 'section sign'},
      {'name': '&shy;',
       'number': '&#173;',
       'description': 'soft hyphen = discretionary hyphen (displays incorrectly on Mac)'},
      {'name': '&sup1;',
       'number': '&#185;',
       'description': 'superscript one = superscript digit one'},
      {'name': '&trade;',
       'number': '&#8482;',
       'description': 'trade mark sign'},
      {'name': '&weierp;',
       'number': '&#8472;',
       'description': 'script capital P = power set = Weierstrass p'},
      {'name': '&bdquo;',
       'number': '&#8222;',
       'description': 'double low-9 quotation mark'},
      {'name': '&laquo;',
       'number': '&#171;',
       'description': 'left-pointing double angle quotation mark = left pointing guillemet'},
      {'name': '&ldquo;',
       'number': '&#8220;',
       'description': 'left double quotation mark'},
      {'name': '&lsaquo;',
       'number': '&#8249;',
       'description': 'single left-pointing angle quotation mark (note)'},
      {'name': '&lsquo;',
       'number': '&#8216;',
       'description': 'left single quotation mark'},
      {'name': '&raquo;',
       'number': '&#187;',
       'description': 'right-pointing double angle quotation mark = right pointing guillemet'},
      {'name': '&rdquo;',
       'number': '&#8221;',
       'description': 'right double quotation mark'},
      {'name': '&rsaquo;',
       'number': '&#8250;',
       'description': 'single right-pointing angle quotation mark (note)'},
      {'name': '&rsquo;',
       'number': '&#8217;',
       'description': 'right single quotation mark'},
      {'name': '&sbquo;',
       'number': '&#8218;',
       'description': 'single low-9 quotation mark'},
      {'name': '&emsp;',
       'number': '&#8195;',
       'description': 'em space'},
      {'name': '&ensp;',
       'number': '&#8194;',
       'description': 'en space'},
      {'name': '&nbsp;',
       'number': '&#160;',
       'description': 'no-break space = non-breaking space'},
      {'name': '&thinsp;',
       'number': '&#8201;',
       'description': 'thin space'},
      {'name': '&zwj;',
       'number': '&#8205;',
       'description': 'zero width joiner'},
      {'name': '&zwnj;',
       'number': '&#8204;',
       'description': 'zero width non-joiner'},
      {'name': '&deg;',
       'number': '&#176;',
       'description': 'degree sign'},
      {'name': '&divide;',
       'number': '&#247;',
       'description': 'division sign'},
      {'name': '&frac12;',
       'number': '&#189;',
       'description': 'vulgar fraction one half = fraction one half'},
      {'name': '&frac14;',
       'number': '&#188;',
       'description': 'vulgar fraction one quarter = fraction one quarter'},
      {'name': '&frac34;',
       'number': '&#190;',
       'description': 'vulgar fraction three quarters = fraction three quarters'},
      {'name': '&ge;',
       'number': '&#8805;',
       'description': 'greater-than or equal to'},
      {'name': '&le;',
       'number': '&#8804;',
       'description': 'less-than or equal to'},
      {'name': '&minus;',
       'number': '&#8722;',
       'description': 'minus sign'},
      {'name': '&sup2;',
       'number': '&#178;',
       'description': 'superscript two = superscript digit two = squared'},
      {'name': '&sup3;',
       'number': '&#179;',
       'description': 'superscript three = superscript digit three = cubed'},
      {'name': '&times;',
       'number': '&#215;',
       'description': 'multiplication sign'},
      {'name': '&alefsym;',
       'number': '&#8501;',
       'description': 'alef symbol = first transfinite cardinal (note)'},
      {'name': '&and;',
       'number': '&#8743;',
       'description': 'logical and = wedge'},
      {'name': '&ang;',
       'number': '&#8736;',
       'description': 'angle'},
      {'name': '&asymp;',
       'number': '&#8776;',
       'description': 'almost equal to = asymptotic to'},
      {'name': '&cap;',
       'number': '&#8745;',
       'description': 'intersection = cap'},
      {'name': '&cong;',
       'number': '&#8773;',
       'description': 'approximately equal to'},
      {'name': '&cup;',
       'number': '&#8746;',
       'description': 'union = cup'},
      {'name': '&empty;',
       'number': '&#8709;',
       'description': 'empty set = null set = diameter'},
      {'name': '&equiv;',
       'number': '&#8801;',
       'description': 'identical to'},
      {'name': '&exist;',
       'number': '&#8707;',
       'description': 'there exists'},
      {'name': '&fnof;',
       'number': '&#402;',
       'description': 'latin small f with hook = function = florin'},
      {'name': '&forall;',
       'number': '&#8704;',
       'description': 'for all'},
      {'name': '&infin;',
       'number': '&#8734;',
       'description': 'infinity'},
      {'name': '&int;',
       'number': '&#8747;',
       'description': 'integral'},
      {'name': '&isin;',
       'number': '&#8712;',
       'description': 'element of'},
      {'name': '&lang;',
       'number': '&#9001;',
       'description': 'left-pointing angle bracket = bra (note)'},
      {'name': '&lceil;',
       'number': '&#8968;',
       'description': 'left ceiling = apl upstile'},
      {'name': '&lfloor;',
       'number': '&#8970;',
       'description': 'left floor = apl downstile'},
      {'name': '&lowast;',
       'number': '&#8727;',
       'description': 'asterisk operator'},
      {'name': '&micro;',
       'number': '&#181;',
       'description': 'micro sign'},
      {'name': '&nabla;',
       'number': '&#8711;',
       'description': 'nabla = backward difference'},
      {'name': '&ne;',
       'number': '&#8800;',
       'description': 'not equal to'},
      {'name': '&ni;',
       'number': '&#8715;',
       'description': 'contains as member (note)'},
      {'name': '&notin;',
       'number': '&#8713;',
       'description': 'not an element of'},
      {'name': '&nsub;',
       'number': '&#8836;',
       'description': 'not a subset of'},
      {'name': '&oplus;',
       'number': '&#8853;',
       'description': 'circled plus = direct sum'},
      {'name': '&or;',
       'number': '&#8744;',
       'description': 'logical or = vee'},
      {'name': '&otimes;',
       'number': '&#8855;',
       'description': 'circled times = vector product'},
      {'name': '&part;',
       'number': '&#8706;',
       'description': 'partial differential'},
      {'name': '&perp;',
       'number': '&#8869;',
       'description': 'up tack = orthogonal to = perpendicular'},
      {'name': '&plusmn;',
       'number': '&#177;',
       'description': 'plus-minus sign = plus-or-minus sign'},
      {'name': '&prod;',
       'number': '&#8719;',
       'description': 'n-ary product = product sign (note)'},
      {'name': '&prop;',
       'number': '&#8733;',
       'description': 'proportional to'},
      {'name': '&radic;',
       'number': '&#8730;',
       'description': 'square root = radical sign'},
      {'name': '&rang;',
       'number': '&#9002;',
       'description': 'right-pointing angle bracket = ket (note)'},
      {'name': '&rceil;',
       'number': '&#8969;',
       'description': 'right ceiling'},
      {'name': '&rfloor;',
       'number': '&#8971;',
       'description': 'right floor'},
      {'name': '&sdot;',
       'number': '&#8901;',
       'description': 'dot operator (note)'},
      {'name': '&sim;',
       'number': '&#8764;',
       'description': 'tilde operator = varies with = similar to (note)'},
      {'name': '&sub;',
       'number': '&#8834;',
       'description': 'subset of'},
      {'name': '&sube;',
       'number': '&#8838;',
       'description': 'subset of or equal to'},
      {'name': '&sum;',
       'number': '&#8721;',
       'description': 'n-ary sumation (note)'},
      {'name': '&sup;',
       'number': '&#8835;',
       'description': 'superset of (note)'},
      {'name': '&supe;',
       'number': '&#8839;',
       'description': 'superset of or equal to'},
      {'name': '&there4;',
       'number': '&#8756;',
       'description': 'therefore'},
      {'name': '&Alpha;',
       'number': '&#913;',
       'description': 'greek capital letter alpha'},
      {'name': '&alpha;',
       'number': '&#945;',
       'description': 'greek small letter alpha'},
      {'name': '&Beta;',
       'number': '&#914;',
       'description': 'greek capital letter beta'},
      {'name': '&beta;',
       'number': '&#946;',
       'description': 'greek small letter beta'},
      {'name': '&Chi;',
       'number': '&#935;',
       'description': 'greek capital letter chi'},
      {'name': '&chi;',
       'number': '&#967;',
       'description': 'greek small letter chi'},
      {'name': '&Delta;',
       'number': '&#916;',
       'description': 'greek capital letter delta'},
      {'name': '&delta;',
       'number': '&#948;',
       'description': 'greek small letter delta'},
      {'name': '&Epsilon;',
       'number': '&#917;',
       'description': 'greek capital letter epsilon'},
      {'name': '&epsilon;',
       'number': '&#949;',
       'description': 'greek small letter epsilon'},
      {'name': '&Eta;',
       'number': '&#919;',
       'description': 'greek capital letter eta'},
      {'name': '&eta;',
       'number': '&#951;',
       'description': 'greek small letter eta'},
      {'name': '&Gamma;',
       'number': '&#915;',
       'description': 'greek capital letter gamma'},
      {'name': '&gamma;',
       'number': '&#947;',
       'description': 'greek small letter gamma'},
      {'name': '&Iota;',
       'number': '&#921;',
       'description': 'greek capital letter iota'},
      {'name': '&iota;',
       'number': '&#953;',
       'description': 'greek small letter iota'},
      {'name': '&Kappa;',
       'number': '&#922;',
       'description': 'greek capital letter kappa'},
      {'name': '&kappa;',
       'number': '&#954;',
       'description': 'greek small letter kappa'},
      {'name': '&Lambda;',
       'number': '&#923;',
       'description': 'greek capital letter lambda'},
      {'name': '&lambda;',
       'number': '&#955;',
       'description': 'greek small letter lambda'},
      {'name': '&Mu;',
       'number': '&#924;',
       'description': 'greek capital letter mu'},
      {'name': '&mu;',
       'number': '&#956;',
       'description': 'greek small letter mu'},
      {'name': '&Nu;',
       'number': '&#925;',
       'description': 'greek capital letter nu'},
      {'name': '&nu;',
       'number': '&#957;',
       'description': 'greek small letter nu'},
      {'name': '&Omega;',
       'number': '&#937;',
       'description': 'greek capital letter omega'},
      {'name': '&omega;',
       'number': '&#969;',
       'description': 'greek small letter omega'},
      {'name': '&Omicron;',
       'number': '&#927;',
       'description': 'greek capital letter omicron'},
      {'name': '&omicron;',
       'number': '&#959;',
       'description': 'greek small letter omicron'},
      {'name': '&Phi;',
       'number': '&#934;',
       'description': 'greek capital letter phi'},
      {'name': '&phi;',
       'number': '&#966;',
       'description': 'greek small letter phi'},
      {'name': '&Pi;',
       'number': '&#928;',
       'description': 'greek capital letter pi'},
      {'name': '&pi;',
       'number': '&#960;',
       'description': 'greek small letter pi'},
      {'name': '&piv;',
       'number': '&#982;',
       'description': 'greek pi symbol'},
      {'name': '&Psi;',
       'number': '&#936;',
       'description': 'greek capital letter psi'},
      {'name': '&psi;',
       'number': '&#968;',
       'description': 'greek small letter psi'},
      {'name': '&Rho;',
       'number': '&#929;',
       'description': 'greek capital letter rho'},
      {'name': '&rho;',
       'number': '&#961;',
       'description': 'greek small letter rho'},
      {'name': '&Sigma;',
       'number': '&#931;',
       'description': 'greek capital letter sigma'},
      {'name': '&sigma;',
       'number': '&#963;',
       'description': 'greek small letter sigma'},
      {'name': '&sigmaf;',
       'number': '&#962;',
       'description': 'greek small letter final sigma (note)'},
      {'name': '&Tau;',
       'number': '&#932;',
       'description': 'greek capital letter tau'},
      {'name': '&tau;',
       'number': '&#964;',
       'description': 'greek small letter tau'},
      {'name': '&Theta;',
       'number': '&#920;',
       'description': 'greek capital letter theta'},
      {'name': '&theta;',
       'number': '&#952;',
       'description': 'greek small letter theta'},
      {'name': '&thetasym;',
       'number': '&#977;',
       'description': 'greek small letter theta symbol'},
      {'name': '&upsih;',
       'number': '&#978;',
       'description': 'greek upsilon with hook symbol'},
      {'name': '&Upsilon;',
       'number': '&#933;',
       'description': 'greek capital letter upsilon'},
      {'name': '&upsilon;',
       'number': '&#965;',
       'description': 'greek small letter upsilon'},
      {'name': '&Xi;',
       'number': '&#926;',
       'description': 'greek capital letter xi'},
      {'name': '&xi;',
       'number': '&#958;',
       'description': 'greek small letter xi'},
      {'name': '&Zeta;',
       'number': '&#918;',
       'description': 'greek capital letter zeta'},
      {'name': '&zeta;',
       'number': '&#950;',
       'description': 'greek small letter zeta'},
      {'name': '&crarr;',
       'number': '&#8629;',
       'description': 'downwards arrow with corner leftwards = carriage return'},
      {'name': '&darr;',
       'number': '&#8595;',
       'description': 'downwards arrow'},
      {'name': '&dArr;',
       'number': '&#8659;',
       'description': 'downwards double arrow'},
      {'name': '&harr;',
       'number': '&#8596;',
       'description': 'left right arrow'},
      {'name': '&hArr;',
       'number': '&#8660;',
       'description': 'left right double arrow'},
      {'name': '&larr;',
       'number': '&#8592;',
       'description': 'leftwards arrow'},
      {'name': '&lArr;',
       'number': '&#8656;',
       'description': 'leftwards double arrow (note)'},
      {'name': '&rarr;',
       'number': '&#8594;',
       'description': 'rightwards arrow'},
      {'name': '&rArr;',
       'number': '&#8658;',
       'description': 'rightwards double arrow (note)'},
      {'name': '&uarr;',
       'number': '&#8593;',
       'description': 'upwards arrow'},
      {'name': '&uArr;',
       'number': '&#8657;',
       'description': 'upwards double arrow'},
      {'name': '&clubs;',
       'number': '&#9827;',
       'description': 'black club suit = shamrock'},
      {'name': '&diams;',
       'number': '&#9830;',
       'description': 'black diamond suit'},
      {'name': '&hearts;',
       'number': '&#9829;',
       'description': 'black heart suit = valentine'},
      {'name': '&spades;',
       'number': '&#9824;',
       'description': 'black spade suit (note)'},
      {'name': '&loz;',
       'number': '&#9674;',
       'description': 'lozenge'}
    ];
  }]);
